DROP SCHEMA IF EXISTS EDOGS CASCADE;

CREATE SCHEMA IF NOT EXISTS EDOGS;

CREATE TABLE IF NOT EXISTS EDOGS.users (
    login TEXT PRIMARY KEY,
    password VARCHAR(32)
);

CREATE TABLE IF NOT EXISTS EDOGS.docs (
    id INTEGER PRIMARY KEY,
    login TEXT,
    title TEXT,
    data TEXT,
    FOREIGN KEY (login) REFERENCES EDOGS.users(login)
);
